const SOCKET = {
  START_CONNECTION: "START_CONNECTION",
  USER_ONLINE: "USER_ONLINE",
  USER_LOGOUT: "USER_LOGOUT",
  USER_CALL_START: "USER_CALL_START",
  USER_CALL_END: "USER_CALL_END",
  CALL_ADD: "CALL_ADD",
  CALL_END: "CALL_END",
  CALL_ADD_CSID: "CALL_ADD_CSID",
} as const;

export default SOCKET;
